name: Build desktop

on:
  push:
    branches: [master]
    paths:
      - "public/**"
      - "src/**"
      - ".github/workflows/desktop.yaml"
      - "package.json"
jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install

    - name: Building app
      run: npm run build

    - name: Packaging Electron app - Windows
      run: npm run package-win
      if: matrix.os == 'windows-2019'
        
    - name: Packaging Electron app - MacOs
      run: npm run package-mac
      if: matrix.os == 'macos-10.15'

    - name: Packaging Electron app - Linux
      run: npm run package-linux
      if: matrix.os == 'ubuntu-18.04'

    - name: get version
      id: package-version
      uses: notiz-dev/github-action-json-property@release
      with:
          path: 'package.json'
          prop_path: 'version'
    
    - uses: actions/upload-artifact@v2
      with:
        name: iota-devnet-wallet-win-${{ steps.package-version.outputs.prop}}
        path: out/iota-devnet-wallet-${{ steps.package-version.outputs.prop}}.exe
      if: matrix.os == 'windows-2019'

    - uses: actions/upload-artifact@v2
      with:
        name: iota-devnet-wallet-mac-${{ steps.package-version.outputs.prop}}
        path: out/iota-devnet-wallet-${{ steps.package-version.outputs.prop}}.dmg
      if: matrix.os == 'macos-10.15'

    - uses: actions/upload-artifact@v2
      with:
        name: iota-devnet-wallet-linux-${{ steps.package-version.outputs.prop}}
        path: |
          out/iota-devnet-wallet-${{ steps.package-version.outputs.prop}}.AppImage
      if: matrix.os == 'ubuntu-18.04'
