name: Build desktop

on:
  push:
    branches: 
      - master

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install dependencies
      run: npm install

    - name: Building app
      run: npm run build

    - name: Packaging Electron app - Windows
      run: npm run package-win
      if: matrix.os == 'windows-2019'
        
    - name: Packaging Electron app - MacOs
      run: npm run package-mac
      if: matrix.os == 'macos-10.15'

    - name: Packaging Electron app - Linux
      run: npm run package-linux
      if: matrix.os == 'ubuntu-18.04'

    - uses: actions/upload-artifact@v2
      with:
        name: pollen-wallet-win
        path: out/pollen-wallet*
      if: matrix.os == 'windows-2019'

    - uses: actions/upload-artifact@v2
      with:
        name: pollen-wallet-mac
        path: out/pollen-wallet*
      if: matrix.os == 'macos-10.15'

    - uses: actions/upload-artifact@v2
      with:
        name: pollen-wallet-linux
        path: out/pollen-wallet*
      if: matrix.os == 'ubuntu-18.04'
