name: Build desktop

on:
  push:
    branches: [master]
    paths:
      - "public/**"
      - "src/**"
      - ".github/workflows/desktop.yaml"
      - "package.json"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install

    - name: Building app
      run: npm run build

    - name: Packaging Electron app - Windows
      run: npm run package-win
      env:
        CSC_LINK: ${{ secrets.WIN_CERT_BASE64 }}
        CSC_KEY_PASSWORD: ${{ secrets.WIN_CERT_PASSWORD }}
      if: matrix.os == 'windows-2019'
        
    - name: Packaging Electron app - MacOs
      run: npm run package-mac
      env:
        CSC_LINK: ${{ secrets.MAC_CERT_BASE64 }}
        CSC_KEY_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
        POLLEN_APPLE_ID: ${{ secrets.APPLE_ID }}
        POLLEN_APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      if: matrix.os == 'macos-10.15'

    - name: Packaging Electron app - Linux
      run: npm run package-linux
      if: matrix.os == 'ubuntu-18.04'

    - name: Import GPG key (Linux)
      run: |
        echo "$GPG_PRIVATE_KEY" | base64 -d > /tmp/private.key && \
        echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 --import /tmp/private.key
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      if: matrix.os == 'ubuntu-18.04'
    
    - name: Sign AppImage (Linux)
      run: echo $GPG_PASSPHRASE | gpg --pinentry-mode loopback --batch --passphrase-fd 0 --armor --detach-sign --default-key contact@iota.org pollen-wallet-*.AppImage
      working-directory: out
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      if: matrix.os == 'ubuntu-18.04'

    - name: get version
      id: package-version
      uses: notiz-dev/github-action-json-property@release
      with:
          path: 'package.json'
          prop_path: 'version'
    
    - uses: actions/upload-artifact@v2
      with:
        name: pollen-wallet-win-${{ steps.package-version.outputs.prop}}
        path: out/pollen-wallet-${{ steps.package-version.outputs.prop}}.exe
      if: matrix.os == 'windows-2019'

    - uses: actions/upload-artifact@v2
      with:
        name: pollen-wallet-mac-${{ steps.package-version.outputs.prop}}
        path: out/pollen-wallet-${{ steps.package-version.outputs.prop}}.dmg
      if: matrix.os == 'macos-10.15'

    - uses: actions/upload-artifact@v2
      with:
        name: pollen-wallet-linux-${{ steps.package-version.outputs.prop}}
        path: |
          out/pollen-wallet-${{ steps.package-version.outputs.prop}}.AppImage
      if: matrix.os == 'ubuntu-18.04'
